Gracie/my collection
IntrepidPursuits/lucien-ios pull request #21
Opened 2017-10-23 19:34 UTC by artsygracie17

Currently the table view isn't scrolling completely. This is just to get the `my_comics` in `My Collection` on the Dashboard; formatting and details are being worked on

2017-10-23 19:46 UTC, IntrepidBuildServer commented
<!--
  0 Errors
  0 Warnings
  2 Messages: Executed 2 tests, with 0 failu...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 2 tests, with 0 failures (0 unexpected) in 0.435 (0.439) seconds</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 1 test, with 0 failures (0 unexpected) in 9.188 (9.190) seconds</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

2017-10-24 13:16 UTC, mayasaxena requested changes

2017-10-24 13:16 UTC, mayasaxena commented on lucien-ios/Models/DashboardComicUser.swift
> +        self.dashboardUser = dashboardUser ?? nil
Don't need the `?? nil` here

2017-10-24 13:16 UTC, mayasaxena commented on lucien-ios/Models/DashboardComicUser.swift
> +        let user = owner ?? borrower ?? nil
Don't need the `?? nil` here

2017-10-24 13:22 UTC, mayasaxena approved these changes

2017-10-24 13:22 UTC, merged