Guled/add comic photo
IntrepidPursuits/lucien-ios pull request #8
Opened 2017-10-05 20:44 UTC by Somnibyte

Here are some fresh new updates. 🎉 

* Added CameraViewController which handles allowing the user to take photos.
* Tapping the *Add Cover Photo* button will take you to the CamerViewController
* iOS asks the user for camera permissions. 

*Note: flash button has not been implemented*

2017-10-05 21:11 UTC, mayasaxena submitted a review, later dismissed
Looks like a good start, but make sure to go through your PR before you put it up and fix the style issues outlined below - you shouldn't have to receive the same piece of feedback more than once.

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/AddNewComicBook/AddComicViewController.swift
> +    private let cameraViewController = CameraViewController()
Need a newline after the MARK

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/AddNewComicBook/AddComicViewController.swift
> +            AVCaptureDevice.requestAccess(for: AVMediaType.video, completionHandler: { (granted: Bool) -> Void in
Use trailing closure syntax in this case. Also there's no need to explicitly define the closure type.

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/AddNewComicBook/AddComicViewController.swift
> +        if AVCaptureDevice.authorizationStatus(for: AVMediaType.video) ==  AVAuthorizationStatus.authorized {
All of the enum types (`AVMediaType`, `AVAuthorizationStatus`) can probably be inferred by the compiler and aren't necessary

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/AddNewComicBook/AddComicViewController.swift
> +            AVCaptureDevice.requestAccess(for: AVMediaType.video, completionHandler: { (granted: Bool) -> Void in
Remove enum type before `.video`

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/AddNewComicBook/AddComicViewController.swift
> +                if granted == true {
Only optional Bools should be compared to true, in this case `if granted` will suffice

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/Camera/CameraViewController.swift
> +    @IBOutlet weak var cameraView: UIView!
This should be private

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/Camera/CameraViewController.swift
> +    private var captureSessionOutput = AVCapturePhotoOutput()
If this is never reassigned, it can be constant

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/Camera/CameraViewController.swift
> +    private var captureSession = AVCaptureSession()
If this is never reassigned, it can be constant

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/Camera/CameraViewController.swift
> +        } catch _ {}
This error should be handled somehow

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/Camera/CameraViewController.swift
> +        cameraView.layer.addSublayer(videoPreviewLayer!)
Don't force unwrap

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/Camera/CameraViewController.swift
> +        let queue = DispatchQueue(label: "com.lucien-ios.captureQueue")
Make this string a constant

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/Camera/CameraViewController.swift
> +
If this implementation will be completed in a later story, a TODO should be added to explain the empty function body. Alternatively, the function should be removed.

2017-10-05 21:11 UTC, mayasaxena commented on lucien-ios/Camera/CameraViewController.swift
> +            if let image = getImageFromSampleBuffer(buffer: sampleBuffer) {}
Why is the body of this `if` empty?

2017-10-09 15:17 UTC, paulrolfe requested changes
Found a crash, but besides that looks good to me.

2017-10-09 15:17 UTC, paulrolfe commented on lucien-ios/AddNewComicBook/AddComicViewController.swift
> +                    self.present(self.cameraViewController, animated: true, completion: nil)
I think this needs to be on the main thread. I was getting a crash on this line in my testing:
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'accessing _cachedSystemAnimationFence requires the main thread'
*** 
First throw call stack:
(0x18e896fe0 0x18d2f8538 0x18e896eb4 0x18f32f760 0x194c44fd0 0x194c9db0c 0x194a827a8 0x1949cf710 0x194a3da80 0x194a3da54 0x194ac26dc 0x194d38440 0x1a304ec80 0x194d39cd0 0x194d3c7e4 0x194ab9794 0x1a304e53c 0x10007ef4c 0x10006f984 0x190aa92f8 0x190aac3d4 0x18d98af30 0x18d98aea0 0x100ffda10 0x10100b990 0x10100d630 0x10100d39c 0x18d957100 0x18d956cac)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

2017-10-09 15:41 UTC, paulrolfe approved these changes

2017-10-09 15:49 UTC, merged